[tool.pyright]
pythonVersion = "3.9"
venvPath = "/home/jma/.virtualenvs/"
venv="jaryo"

[tool.pyright.analysis]
typeCheckingMode = "strict"

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120