# Generated by Django 4.2.1 on 2023-05-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_email_user_email_address_user_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_address",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
